### ISSUE TITLE
锁屏时钟红色"1"

### ISSUE THREAD

**Issue by bugme2** [Oosl/ColorOSTool#1]
能添加一个屏蔽这玩意的功能吗

**Comment by Oosl** [comment]
讲道理，原理上应该是可以的。至于我能不能做出来，有待验证，我可以试试🌚

**Comment by Oosl** [comment]
> 能添加一个屏蔽这玩意的功能吗

2b37e3ad307c8577b743bfd096189c86876d59c9
最新版已添加此功能。

**Comment by Oosl** [comment]
> > 讲道理，原理上应该是可以的。🌚
> 
> 嘿嘿，能修改一下状态栏网速刷新率就更好了，刷新太慢了，看网速不准

这个我后面再看看吧，感觉需求不是很大。先把这个issue关了

**Comment by bugme2** [comment]
> > > 讲道理，原理上应该是可以的。🌚
> > 
> > 
> > 嘿嘿，修改一下状态栏网速刷新率就提高了，刷新太慢了，看网不准
> 
> 这个我再看看吧，感觉需求不是我的。先把这个问题关了

那搞一个充电小数点常驻？这个也不错。
