### ISSUE TITLE
[适配请求] RealmeUI2.0

### ISSUE THREAD

**Issue by byxiaorun** [Oosl/ColorOSTool#10]
APK安装器里面的功能无效其实我只要apk安装器的功能就好，感谢作者，附系统界面   [8.0.0].apk，设置   [7.0.11].apk，应用包安装程序   [3.3.2414].apk，请求适配
https://byxiaorun.lanzoui.com/b00v1598f
密码:color

**Comment by Oosl** [comment]
看到酷安有人11可以安装12的安装器，你要不试试？这样就能直接生效了😂
