### ISSUE TITLE
申请支持 Realme 國際版和印度版

### ISSUE THREAD

**Issue by k2913064** [Oosl/ColorOSTool#11]
realme gt國際版無法使用
希望可以新增國際版和印度版的支持
謝謝

**Comment by Oosl** [comment]
是安卓11吗？是的话试试[1.7.0版本](https://github.com/Xposed-Modules-Repo/com.oosl.colorostool/releases/tag/9-1.7)

**Comment by k2913064** [comment]
謝謝作者
是安卓11沒錯，只不過是國際版不是中國版😀
最新版1.8.8測試120hz可以使用
但其他功能還是沒效果，比如說自動啟動管理
國際版和中國版的設置好像不一樣，是限制20個
![Screenshot_2021-11-22-03-11-55-47](https://user-images.githubusercontent.com/24394382/142775796-8e3fc70e-0f3a-4e88-9043-f9c2b5c20bc1.jpg)
希望能適配😆謝謝您

**Comment by Oosl** [comment]
好吧，首先很抱歉，由于我手里只有一加9 Pro-中国大陆版。所以我基本只考虑适配该手机上的版本。OPPO系其他系列是否能用全靠缘分，目前我没有想法花精力去适配其他系列。（你也看到了，一加安卓11我甚至都放弃了适配）
另外系统是安卓11，请务必使用1.7.0版本，后续版本我去掉了兼容安卓11的代码，但是最终是否能用，也如上所说，随缘。
Sorry~

**Comment by k2913064** [comment]
不用對不起XD很謝謝作者開發那麼好用的模組
1.7版本有試過還是不行，目前測試120HZ可以執行
但關不掉，就算取消勾勾也沒有作用，希望可以更新，謝謝

**Comment by Oosl** [comment]
你所说的关不掉指的是？  
- 关闭120hz功能开关后，每次进入设置还是会触发模块的120hz设置？
- 关闭120hz功能开关后，系统不会从全局120hz回到设置前的状态?    

如果是前者请检查你是否使用的Lsposed，这个设置开关状态依赖Lsposed的一个特性。
如果是后者，这是目前预期的行为，关掉仅仅只是不会再设置120hz，并不会回复系统状态，你可以通过切换系统的刷新率选项来恢复。

**Comment by k2913064** [comment]
作者您好
就是指強制120hz後，就算在模組內關閉強制120的功能
系統還是一樣強制120hz無法降為60hz
就算模組取消勾選和到顯示那邊設定為60hz還是不能變降為60
而且每次只要進螢幕頻率設定就會跳出120hz已啟用😀

**Comment by Oosl** [comment]
模块内关闭功能后，需要强行停止设置，模块才会停止失效
