### ISSUE TITLE
Cannot install on OP 9RT

### ISSUE THREAD

**Issue by XiJingPooh** [Oosl/ColorOSTool#12]
Cannot install on OnePlus 9RT
Version 1.8.12

![Screenshot_2022-01-03-16-57-37-18_bb8ece83317b06ec453d187d61792a56](https://user-images.githubusercontent.com/74847875/148003757-d50d2d51-9b9b-4099-8b23-757f051716ed.jpg)

![Screenshot_2022-01-03-17-00-20-30_fc704e6b13c4fb26bf5e411f75da84f2](https://user-images.githubusercontent.com/74847875/148003922-e89989e7-dde6-4443-9642-2f4c21c174ba.jpg)

**Comment by Oosl** [comment]
try the latest version

**Comment by XiJingPooh** [comment]
Works perfectly!  Thank you.
