### ISSUE TITLE
Package installer doesn't work

### ISSUE THREAD

**Issue by XiJingPooh** [Oosl/ColorOSTool#14]
Package installer options to bypass scanning, identity verification, banner, and to use aosp installer doesn't work.

Version 1.8.13

**Comment by Oosl** [comment]
which version Package installer you use? upload it to here.

**Comment by XiJingPooh** [comment]
I want to use the default aosp installer, but it still uses the coloros installer.

**Comment by XiJingPooh** [comment]
Even if I use the coloros installer, the option to skip virus scanning and identity verification doesn't work.

**Comment by XiJingPooh** [comment]
@nickolasclarke I wasn't able to ever get it working, but found a workaround.
1: Let the install fail since you can't sign in to identify yourself.
2: Open phone manager and go to the antivirus section.
3: Ignore the risk that it flagged.
4: install as normal.

It's a hassle, but does work.

I no longer have this problem since I converted the phone from coloros to oxygenos, but the problem still exists in this app so I didn't close this issue.
[https://forum.xda-developers.com/t/rom-indian-oxygenos11.4390243/page-2#post-86374331](url)

**Comment by nickolasclarke** [comment]
@XiJingPooh how did you convert to oxygen? I saw discussion in that thread about differences in partitioning between the two OS and that it's not as straightforward as a normal flash. This is the wrong place to hash this out but reach out to me on Twitter (same username) or email nickolasclarke at gmail

**Comment by nickolasclarke** [comment]
Oh followed the link and i see the guide. Sorry.

**Comment by nickolasclarke** [comment]
I'm afraid I also moved to the indian OxygenOS rom, so I do not have access
to which version I had any longer as well. Sorry.
