### ISSUE TITLE
c62上启用布局拓展 点击布局桌面会崩溃

### ISSUE THREAD

**Issue by Ayaya233** [Oosl/ColorOSTool#23]
[抓的Error](https://github.com/Oosl/ColorOSTool/files/8583593/error.log)

**Comment by Oosl** [comment]
已知问题，桌面布局改版了，这个功能暂时不能用，不过TG群里最新版不会闪退。

**Comment by Oosl** [comment]
不对，之前是C61的，C62可能又有改动吧，后面看一下
