### ISSUE TITLE
[功能请求] 增加 关闭应用安装完毕后的商店入口

### ISSUE THREAD

**Issue by NextAlone** [Oosl/ColorOSTool#3]
增加 关闭应用安装完毕后的商店入口（Color OS 12）

![Screenshot_2021-09-30-22-28-42-56_bb8ece83317b06ec453d187d61792a56](https://user-images.githubusercontent.com/12210746/135474703-883c9a22-27bc-4f9e-8a3f-7357605269ca.jpg)

如上图中间所示

**Comment by Oosl** [comment]
OK，这个有在计划内

**Comment by Oosl** [comment]
99091a3e4146f0a2f7844c84f6ee6f3d2ee8f995

**Comment by NextAlone** [comment]
还是有的
![Screenshot_2021-10-09-02-08-22-66_bb8ece83317b06ec453d187d61792a56.jpg](https://user-images.githubusercontent.com/12210746/136602976-6789f8a6-5a8d-406a-8d92-f906e5448a73.jpg)
