### ISSUE TITLE
[功能请求] 移除VPN等通知

### ISSUE THREAD

**Issue by NextAlone** [Oosl/ColorOSTool#8]
如下图中所示两条通知，不可隐藏

![Screenshot_2021-10-22-05-11-10-42_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/12210746/138357385-6fb7e7a6-cc45-4cd1-af46-d008568aa337.jpg)
![Screenshot_2021-10-22-05-11-01-03_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/12210746/138357381-d2c72c30-84c1-4b78-afdb-d98b9a899588.jpg)

**Comment by Oosl** [comment]
想搞，但是还不知道怎么搞，看缘分

**Comment by Oosl** [comment]
[WooBoxForColorOS](https://github.com/Simplicity-Team/WooBoxForColorOS)
