### ISSUE TITLE
[功能请求] QHD+下补帧到120Hz

### ISSUE THREAD

**Issue by NextAlone** [Oosl/ColorOSTool#9]
现仅支持FHD+下补帧到120hz

![Screenshot_2021-10-22-05-13-08-83_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/12210746/138357591-955cc29d-76fb-4f1f-959c-a67e5f343e3f.jpg)
![Screenshot_2021-10-22-05-14-34-56_fc704e6b13c4fb26bf5e411f75da84f2.jpg](https://user-images.githubusercontent.com/12210746/138357745-ef40409d-8e5f-4f4e-81b9-635508e4c2dc.jpg)

**Comment by Oosl** [comment]
感觉没啥用，不想搞

**Comment by Oosl** [comment]
摆烂了
